version: mark21
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

network:
  forwarded_ports: ["3000"]

handlers:

- url: /(.*\.(html|css|js))
  static_files: public/\1
  upload: public/(.*\.(html|css|js))

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /.*
  script: app.js
